### 密码模式，请求AuthParamsDto参数
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"password":"1234","authType":"password","cellphone":"1649"}

###测试redis
GET {{gateway}}/user/open/redis

###发送验证码
GET {{gateway}}/user/open/sedsms/18876521895

###注册
POST {{gateway}}/user/open/logon
Content-Type: application/json

{
  "userPhone":"11111111111",
  "userPassward":"1234",
  "userName":"yuyuyuyuu",
  "sms":"12"
}

###退出
GET {{gateway}}/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJ1c2VySWRcIjpcIjc3ODIwNzA2YjE3ODExYTJkNjVjMzMxNGQyNWJhZGYwXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4MjE3NzgyNSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiJmNjRlODI3NC1iODQ5LTQ1MTgtODUwYi1mYWNmYTRhOGIyOTEiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.106cqfB8r0ARWclmV7GK6srbz3v0xg8EQdEPsSjNTLA

###测试
GET {{gateway}}/user/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJ1c2VySWRcIjpcIjc3ODIwNzA2YjE3ODExYTJkNjVjMzMxNGQyNWJhZGYwXCIsXCJ1c2VyUGhvbmVcIjpcIjE2NDlcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjgyMTg3NDU1LCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6ImY1ZmRlODA2LWJmNDItNDVmZi1iNWQxLWE5MjQ0ZWZmOTE2YiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.0-lCLkO4Nwc81ScYOCRNLwM__N6dK7hPJW8EKq4P3Uw
###发布商品
POST {{gateway}}/shop/mess/up
Content-Type: application/json

{
  "shopName":"7yyy77",
  "shopIntuoduct":"ASS",
  "shopPrice":"89",
  "shopBuy":"0"
}

###获取所有商品
GET  {{gateway}}/shop/mess/get/1

###修改用户信息
POST {{gateway}}/user/upuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJ1c2VyQ3JlYXRlVGltZVwiOjE2ODIxMDk0ODYwMDAsXCJ1c2VySWRcIjpcIjc3ODIwNzA2YjE3ODExYTJkNjVjMzMxNGQyNWJhZGYwXCIsXCJ1c2VyTmFtZVwiOlwieHh4c2FcIixcInVzZXJQaG9uZVwiOlwiMTY0OVwiLFwidXNlclVwZGF0ZVRpbWVcIjoxNjgyMTEwODE0MDAwfSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODIwODk3NDIsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiNDIzYWIyOTgtNzQ2Ny00OTFlLWE3Y2MtZjNjZmE1NThiMWQ2IiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.qroxboMCUvjb_1eAQ7FyKFPUuXaMSKutg3P5eIXF6Do
Content-Type: application/json

{
  "userName":"asas",
  "userEmail":"a@asdfa",
  "userIntroduct":"asdasda",
  "userSchool":"中国海洋大学",
  "userSex":"男",
  "userAge":"12"
}

###退出
GET {{gateway}}/auth/oauth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJ1c2VyQWdlXCI6MTIsXCJ1c2VyQ3JlYXRlVGltZVwiOjE2ODIxMDk0ODYwMDAsXCJ1c2VyRW1haWxcIjpcImFAYXNkZmFcIixcInVzZXJJZFwiOlwiNzc4MjA3MDZiMTc4MTFhMmQ2NWMzMzE0ZDI1YmFkZjBcIixcInVzZXJJbnRyb2R1Y3RcIjpcImFzZGFzZGFcIixcInVzZXJOYW1lXCI6XCJhc2FzXCIsXCJ1c2VyUGhvbmVcIjpcIjE2NDlcIixcInVzZXJTY2hvb2xcIjpcIuS4reWbvea1t-a0i-Wkp-WtplwiLFwidXNlclNleFwiOlwi55S3XCIsXCJ1c2VyVXBkYXRlVGltZVwiOjE2ODIxMTEzNjgwMDB9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4MjA5MTIyOCwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI5OGNjNjA2MS1kYmRkLTQ0YTItYTg3Ny1mZWZlNDMzZTliOGYiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.5foy2n6ngr6slmHHUGJ-KmFjAIB_uNmhCADKN4iAHQM