###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJ1c2VyQWdlXCI6MTksXCJ1c2VyQXZhdGFyXCI6XCJodHRwcy8vOnh4eHgueHh4eFwiLFwidXNlckNyZWF0ZVRpbWVcIjoxNjgwNTE5ODYxMDAwLFwidXNlckVtYWlsXCI6XCIxMjM0NTZAZW1haWwuY29tXCIsXCJ1c2VySWRcIjpcIjB4MDAwMDkxMjdcIixcInVzZXJJbnRyb2R1Y3RcIjpcIm51bGxcIixcInVzZXJOYW1lXCI6XCJ6aGFuZ3NhblwiLFwidXNlclBob25lXCI6XCIxMjMzMzMzMzMzM1wiLFwidXNlclNleFwiOlwi55S3XCIsXCJ1c2VyU3RhdHVzXCI6XCLmraPluLhcIixcInVzZXJUeXBlXCI6XCLnrqHnkIblkZhcIixcInVzZXJVcGRhdGVUaW1lXCI6MTY4MDUxOTg3ODAwMH0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjgxMzEyNTMyLCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjJlNmQ4NGYzLTkxNWMtNDRjOC1iNTgwLWM4NTIzZmIwOGYyOSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.LDV6vRZhJ-JXj9-m73nbA8zINFN1SgpukOJZINy_pk8

### 密码模式，请求AuthParamsDto参数
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"password":"test","authType":"password","cellphone":"12333333333"}

###
GET {{gateway}}/user/x
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJ1c2VyQWdlXCI6MTksXCJ1c2VyQXZhdGFyXCI6XCJodHRwcy8vOnh4eHgueHh4eFwiLFwidXNlckNyZWF0ZVRpbWVcIjoxNjgwNTE5ODYxMDAwLFwidXNlckVtYWlsXCI6XCIxMjM0NTZAZW1haWwuY29tXCIsXCJ1c2VySWRcIjpcIjB4MDAwMDkxMjdcIixcInVzZXJJbnRyb2R1Y3RcIjpcIm51bGxcIixcInVzZXJOYW1lXCI6XCJ6aGFuZ3NhblwiLFwidXNlclBob25lXCI6XCIxMjMzMzMzMzMzM1wiLFwidXNlclNleFwiOlwi55S3XCIsXCJ1c2VyU3RhdHVzXCI6XCLmraPluLhcIixcInVzZXJUeXBlXCI6XCLnrqHnkIblkZhcIixcInVzZXJVcGRhdGVUaW1lXCI6MTY4MDUxOTg3ODAwMH0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjgxMzEyNTMyLCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjJlNmQ4NGYzLTkxNWMtNDRjOC1iNTgwLWM4NTIzZmIwOGYyOSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.LDV6vRZhJ-JXj9-m73nbA8zINFN1SgpukOJZINy_pk8

###注册
POST {{gateway}}/user/logon
Content-Type: application/json

{
  "userPhone":"12111111111",
  "userPassward":"90909090909",
  "userName":"aisdhia",
  "sms":"12"
}